### ISSUE TITLE
use nvim as backend for jetbrains

### ISSUE THREAD

**Issue by astier** [beeender/Comrade#11]
Hi. This is a very nice plugin. However, it feels awkward to have both jetbrains and nvim open at the same time to have completion etc. in nvim provided be jetbrains. How about the other way around? Since nvim provides an api to use it as a backend for any UI it should be theoretically possible to have just open jetbrains with all its feautures but with the editing capabilities of nvim. An example from the real world would be [vscode-neovim](https://github.com/asvetliakov/vscode-neovim). It works in vscode! You have all the advantages of working directly in vscode but also the power of real nvim and all its plugins. What do you think?

**Comment by beeender** [comment]
Yeah, I have thought about it, it is possible to do that. And some code of this project can be reused for that purpose.
However it will be a lot more work needed, not sure if I have time for that :P

There was a ticket raised long time ago in the JetBrain's issue tracker https://youtrack.jetbrains.com/issue/VIM-858 for the same purpose.

**Comment by astier** [comment]
Thanks. I wrote a comment also on the issue. Maybe it should be better if they would implement it. I don't know. Close this issue if you want.
