### ISSUE TITLE
Exposing jump to definition

### ISSUE THREAD

**Issue by PatOConnor43** [beeender/Comrade#2]
Hi, first I just want to say that this is a really cool project! Are there any plans to allow jumping to definition from this plugin or maybe the intelliJ plugin could expose a language server api to do refactoring, find references, etc.

Thanks!

**Comment by beeender** [comment]
Yes, GOTO feature is planned. But exposing LSP api is not.

Exposing LSP adds some complexity to both sides of the plugins. This project only aims to build a connection between IntelliJ and Nvim and make it easy to use.
If you are looking for a LSP for IntelliJ, check [this project](https://github.com/gtache/intellij-lsp).
