### ISSUE TITLE
Complete information is not complete

### ISSUE THREAD

**Issue by denstiny** [beeender/Comrade#25]
https://user-images.githubusercontent.com/57088952/111897560-87353400-8a5b-11eb-8aca-a4e92900bf61.mp4

**Comment by beeender** [comment]
Yes, that is a known issue ... Unfortunately there is some mystery with JetBrain's completion system which I don't quite understand.
Let's see if I get time to improve it in the future.

Thanks for reporting!!!

**Comment by denstiny** [comment]
All right, print you.
